"""Added to User table

Revision ID: 333f01e580eb
Revises: 3fdd6b30d1bf
Create Date: 2022-08-22 11:19:58.303942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333f01e580eb'
down_revision = '3fdd6b30d1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_num', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('contact_pref', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact_pref')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'phone_num')
    # ### end Alembic commands ###
