"""Added notification settings to User

Revision ID: 3fdd6b30d1bf
Revises: 676269e057a9
Create Date: 2022-08-22 10:55:31.440668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdd6b30d1bf'
down_revision = '676269e057a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_change_notify', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('holds_notify', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('watchlist_notify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'watchlist_notify')
    op.drop_column('user', 'holds_notify')
    op.drop_column('user', 'account_change_notify')
    # ### end Alembic commands ###
